Allow animated materials on Mario instance
JoshuaMKW/BetterSunshineEngine pull request #34
Opened 2024-09-15 20:20 UTC by TheAzack9

This allows for e.g Shadow Mario to be created as a mario skin. With the inclusion of this you can add e.g btk animations to mario. It is all optinally feature toggled from the model and the original mario model works by default.

Currently i've added two prm paramters for this. One for adding a MActor to mario and another for replacing a specific material with the screen texture. (This is to support Shadow Mario, but can technically be used by other models as well)

I've attached some example skins that i've used to test this. 
[mario_skins.zip](https://github.com/user-attachments/files/17007312/mario_skins.zip)

2024-09-15 20:40 UTC, JoshuaMKW approved these changes
This solution is surprisingly elegant, great work, I'll merge it soon.

2024-11-24 16:47 UTC, TheAzack9 commented
This technically only supported animated materials on ma_mdl1, but that was a bit limiting according to MasterMario.
I added the rest of the bodyparts as well.

embedded mario skins no longer works due to change in naming. Instead of calling btk e.g `/mario/custom/default.btk` it is now named by the part. So it should be `/mario/custom/ma_mdl1.btk` for the generic mario model.

2024-11-28 22:14 UTC, JoshuaMKW requested changes
You should also run the clang-format configuration on these files to normalize with the rest of the repository.

2024-11-28 22:14 UTC, JoshuaMKW commented on src/player.cpp
> +    if(params->mMActor[0]) {
Change this to check for each MActor individually within the loop because that's safer and also more flexible.

2024-11-28 22:14 UTC, JoshuaMKW commented on src/player.cpp
> +    if(params->mMActor[0]) {
Refer to comment on line 876 ^^

2024-11-28 22:14 UTC, JoshuaMKW commented on src/player.cpp
>              if(finder != 0x0) {
Change these comparisons from 0x0 to nullptr which is more correct and explicit to read.

2024-11-29 22:11 UTC, TheAzack9 commented
Should be fixed now 😊

2024-11-29 22:34 UTC, JoshuaMKW approved these changes

2024-11-29 22:34 UTC, merged